/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as staking from "./staking";
export type { staking };
export type { SwapFeeCollector } from "./SwapFeeCollector";
export type { SwapReferralRewards } from "./SwapReferralRewards";
