/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace LexaStaking {
  export type TierConfigStruct = {
    minStakeAmount: BigNumberish;
    roi90days: BigNumberish;
    roi180days: BigNumberish;
  };

  export type TierConfigStructOutput = [
    minStakeAmount: bigint,
    roi90days: bigint,
    roi180days: bigint
  ] & { minStakeAmount: bigint; roi90days: bigint; roi180days: bigint };

  export type UserStakeStruct = {
    amount: BigNumberish;
    lockDurationDays: BigNumberish;
    startTimestamp: BigNumberish;
    tier: BigNumberish;
    totalRewardsEntitled: BigNumberish;
    totalRewardsClaimed: BigNumberish;
    active: boolean;
  };

  export type UserStakeStructOutput = [
    amount: bigint,
    lockDurationDays: bigint,
    startTimestamp: bigint,
    tier: bigint,
    totalRewardsEntitled: bigint,
    totalRewardsClaimed: bigint,
    active: boolean
  ] & {
    amount: bigint;
    lockDurationDays: bigint;
    startTimestamp: bigint;
    tier: bigint;
    totalRewardsEntitled: bigint;
    totalRewardsClaimed: bigint;
    active: boolean;
  };
}

export interface LexaStakingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimRewards"
      | "emergencyRecoverTokens"
      | "fundRewardPool"
      | "getAccumulatedRewards"
      | "getActiveStakeCount"
      | "getTierConfig"
      | "getTotalLockedAmount"
      | "getUserStakes"
      | "hasUsedReferrer"
      | "isStakeMatured"
      | "lexaToken"
      | "owner"
      | "pause"
      | "paused"
      | "referralRewardAmount"
      | "referralRewardsClaimed"
      | "renounceOwnership"
      | "restakeRewards"
      | "rewardPoolBalance"
      | "setReferralRewardAmount"
      | "setStakingPaused"
      | "stake"
      | "stakerReferrer"
      | "stakingPaused"
      | "tiers"
      | "transferOwnership"
      | "unpause"
      | "unstake"
      | "updateTierConfig"
      | "userStakeCount"
      | "userStakes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyTokenRecovery"
      | "OwnershipTransferred"
      | "Paused"
      | "ReferralRewardAmountUpdated"
      | "ReferralRewarded"
      | "RewardPoolFunded"
      | "RewardsClaimed"
      | "RewardsRestaked"
      | "Staked"
      | "StakingPausedToggled"
      | "Unpaused"
      | "Unstaked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyRecoverTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundRewardPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccumulatedRewards",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveStakeCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTierConfig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalLockedAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStakes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUsedReferrer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isStakeMatured",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "lexaToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "referralRewardAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referralRewardsClaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "restakeRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPoolBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setReferralRewardAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [BigNumberish, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakerReferrer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingPaused",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tiers", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTierConfig",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userStakeCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userStakes",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyRecoverTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundRewardPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccumulatedRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveStakeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTierConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalLockedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUsedReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isStakeMatured",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lexaToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "referralRewardAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralRewardsClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restakeRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardPoolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReferralRewardAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakerReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tiers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTierConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userStakeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userStakes", data: BytesLike): Result;
}

export namespace EmergencyTokenRecoveryEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    recipient: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    amount: bigint,
    recipient: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    token: string;
    amount: bigint;
    recipient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralRewardAmountUpdatedEvent {
  export type InputTuple = [newAmount: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [newAmount: bigint, timestamp: bigint];
  export interface OutputObject {
    newAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralRewardedEvent {
  export type InputTuple = [
    referrer: AddressLike,
    newStaker: AddressLike,
    rewardAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    referrer: string,
    newStaker: string,
    rewardAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    referrer: string;
    newStaker: string;
    rewardAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardPoolFundedEvent {
  export type InputTuple = [
    funder: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [funder: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    stakeIndex: BigNumberish,
    rewardsAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    stakeIndex: bigint,
    rewardsAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    stakeIndex: bigint;
    rewardsAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsRestakedEvent {
  export type InputTuple = [
    user: AddressLike,
    stakeIndex: BigNumberish,
    rewardAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    stakeIndex: bigint,
    rewardAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    stakeIndex: bigint;
    rewardAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    user: AddressLike,
    tier: BigNumberish,
    amount: BigNumberish,
    lockDurationDays: BigNumberish,
    totalRewardsEntitled: BigNumberish,
    referrer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tier: bigint,
    amount: bigint,
    lockDurationDays: bigint,
    totalRewardsEntitled: bigint,
    referrer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    tier: bigint;
    amount: bigint;
    lockDurationDays: bigint;
    totalRewardsEntitled: bigint;
    referrer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakingPausedToggledEvent {
  export type InputTuple = [isPaused: boolean, timestamp: BigNumberish];
  export type OutputTuple = [isPaused: boolean, timestamp: bigint];
  export interface OutputObject {
    isPaused: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    user: AddressLike,
    stakeIndex: BigNumberish,
    principalAmount: BigNumberish,
    unclaimedRewards: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    stakeIndex: bigint,
    principalAmount: bigint,
    unclaimedRewards: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    stakeIndex: bigint;
    principalAmount: bigint;
    unclaimedRewards: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LexaStaking extends BaseContract {
  connect(runner?: ContractRunner | null): LexaStaking;
  waitForDeployment(): Promise<this>;

  interface: LexaStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimRewards: TypedContractMethod<
    [_stakeIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyRecoverTokens: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundRewardPool: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAccumulatedRewards: TypedContractMethod<
    [_user: AddressLike, _stakeIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getActiveStakeCount: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  getTierConfig: TypedContractMethod<
    [_tier: BigNumberish],
    [LexaStaking.TierConfigStructOutput],
    "view"
  >;

  getTotalLockedAmount: TypedContractMethod<[], [bigint], "view">;

  getUserStakes: TypedContractMethod<
    [_user: AddressLike],
    [LexaStaking.UserStakeStructOutput[]],
    "view"
  >;

  hasUsedReferrer: TypedContractMethod<
    [staker: AddressLike],
    [boolean],
    "view"
  >;

  isStakeMatured: TypedContractMethod<
    [_user: AddressLike, _stakeIndex: BigNumberish],
    [boolean],
    "view"
  >;

  lexaToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  referralRewardAmount: TypedContractMethod<[], [bigint], "view">;

  referralRewardsClaimed: TypedContractMethod<
    [referrer: AddressLike],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  restakeRewards: TypedContractMethod<
    [_stakeIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  rewardPoolBalance: TypedContractMethod<[], [bigint], "view">;

  setReferralRewardAmount: TypedContractMethod<
    [_newAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setStakingPaused: TypedContractMethod<
    [_isPaused: boolean],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<
    [
      _amount: BigNumberish,
      _tier: BigNumberish,
      _durationDays: BigNumberish,
      _referrer: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  stakerReferrer: TypedContractMethod<[staker: AddressLike], [string], "view">;

  stakingPaused: TypedContractMethod<[], [boolean], "view">;

  tiers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        minStakeAmount: bigint;
        roi90days: bigint;
        roi180days: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  unstake: TypedContractMethod<
    [_stakeIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateTierConfig: TypedContractMethod<
    [
      _tier: BigNumberish,
      _minStake: BigNumberish,
      _roi90d: BigNumberish,
      _roi180d: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  userStakeCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  userStakes: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        amount: bigint;
        lockDurationDays: bigint;
        startTimestamp: bigint;
        tier: bigint;
        totalRewardsEntitled: bigint;
        totalRewardsClaimed: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[_stakeIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyRecoverTokens"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundRewardPool"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAccumulatedRewards"
  ): TypedContractMethod<
    [_user: AddressLike, _stakeIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveStakeCount"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTierConfig"
  ): TypedContractMethod<
    [_tier: BigNumberish],
    [LexaStaking.TierConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalLockedAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserStakes"
  ): TypedContractMethod<
    [_user: AddressLike],
    [LexaStaking.UserStakeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUsedReferrer"
  ): TypedContractMethod<[staker: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isStakeMatured"
  ): TypedContractMethod<
    [_user: AddressLike, _stakeIndex: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lexaToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "referralRewardAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "referralRewardsClaimed"
  ): TypedContractMethod<[referrer: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "restakeRewards"
  ): TypedContractMethod<[_stakeIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardPoolBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setReferralRewardAmount"
  ): TypedContractMethod<[_newAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakingPaused"
  ): TypedContractMethod<[_isPaused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [
      _amount: BigNumberish,
      _tier: BigNumberish,
      _durationDays: BigNumberish,
      _referrer: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakerReferrer"
  ): TypedContractMethod<[staker: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "stakingPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "tiers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        minStakeAmount: bigint;
        roi90days: bigint;
        roi180days: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[_stakeIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTierConfig"
  ): TypedContractMethod<
    [
      _tier: BigNumberish,
      _minStake: BigNumberish,
      _roi90d: BigNumberish,
      _roi180d: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userStakeCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userStakes"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        amount: bigint;
        lockDurationDays: bigint;
        startTimestamp: bigint;
        tier: bigint;
        totalRewardsEntitled: bigint;
        totalRewardsClaimed: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "EmergencyTokenRecovery"
  ): TypedContractEvent<
    EmergencyTokenRecoveryEvent.InputTuple,
    EmergencyTokenRecoveryEvent.OutputTuple,
    EmergencyTokenRecoveryEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralRewardAmountUpdated"
  ): TypedContractEvent<
    ReferralRewardAmountUpdatedEvent.InputTuple,
    ReferralRewardAmountUpdatedEvent.OutputTuple,
    ReferralRewardAmountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralRewarded"
  ): TypedContractEvent<
    ReferralRewardedEvent.InputTuple,
    ReferralRewardedEvent.OutputTuple,
    ReferralRewardedEvent.OutputObject
  >;
  getEvent(
    key: "RewardPoolFunded"
  ): TypedContractEvent<
    RewardPoolFundedEvent.InputTuple,
    RewardPoolFundedEvent.OutputTuple,
    RewardPoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsRestaked"
  ): TypedContractEvent<
    RewardsRestakedEvent.InputTuple,
    RewardsRestakedEvent.OutputTuple,
    RewardsRestakedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "StakingPausedToggled"
  ): TypedContractEvent<
    StakingPausedToggledEvent.InputTuple,
    StakingPausedToggledEvent.OutputTuple,
    StakingPausedToggledEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;

  filters: {
    "EmergencyTokenRecovery(address,uint256,address,uint256)": TypedContractEvent<
      EmergencyTokenRecoveryEvent.InputTuple,
      EmergencyTokenRecoveryEvent.OutputTuple,
      EmergencyTokenRecoveryEvent.OutputObject
    >;
    EmergencyTokenRecovery: TypedContractEvent<
      EmergencyTokenRecoveryEvent.InputTuple,
      EmergencyTokenRecoveryEvent.OutputTuple,
      EmergencyTokenRecoveryEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReferralRewardAmountUpdated(uint256,uint256)": TypedContractEvent<
      ReferralRewardAmountUpdatedEvent.InputTuple,
      ReferralRewardAmountUpdatedEvent.OutputTuple,
      ReferralRewardAmountUpdatedEvent.OutputObject
    >;
    ReferralRewardAmountUpdated: TypedContractEvent<
      ReferralRewardAmountUpdatedEvent.InputTuple,
      ReferralRewardAmountUpdatedEvent.OutputTuple,
      ReferralRewardAmountUpdatedEvent.OutputObject
    >;

    "ReferralRewarded(address,address,uint256,uint256)": TypedContractEvent<
      ReferralRewardedEvent.InputTuple,
      ReferralRewardedEvent.OutputTuple,
      ReferralRewardedEvent.OutputObject
    >;
    ReferralRewarded: TypedContractEvent<
      ReferralRewardedEvent.InputTuple,
      ReferralRewardedEvent.OutputTuple,
      ReferralRewardedEvent.OutputObject
    >;

    "RewardPoolFunded(address,uint256,uint256)": TypedContractEvent<
      RewardPoolFundedEvent.InputTuple,
      RewardPoolFundedEvent.OutputTuple,
      RewardPoolFundedEvent.OutputObject
    >;
    RewardPoolFunded: TypedContractEvent<
      RewardPoolFundedEvent.InputTuple,
      RewardPoolFundedEvent.OutputTuple,
      RewardPoolFundedEvent.OutputObject
    >;

    "RewardsClaimed(address,uint256,uint256,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "RewardsRestaked(address,uint256,uint256,uint256)": TypedContractEvent<
      RewardsRestakedEvent.InputTuple,
      RewardsRestakedEvent.OutputTuple,
      RewardsRestakedEvent.OutputObject
    >;
    RewardsRestaked: TypedContractEvent<
      RewardsRestakedEvent.InputTuple,
      RewardsRestakedEvent.OutputTuple,
      RewardsRestakedEvent.OutputObject
    >;

    "Staked(address,uint8,uint256,uint256,uint256,address,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "StakingPausedToggled(bool,uint256)": TypedContractEvent<
      StakingPausedToggledEvent.InputTuple,
      StakingPausedToggledEvent.OutputTuple,
      StakingPausedToggledEvent.OutputObject
    >;
    StakingPausedToggled: TypedContractEvent<
      StakingPausedToggledEvent.InputTuple,
      StakingPausedToggledEvent.OutputTuple,
      StakingPausedToggledEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Unstaked(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
  };
}
